name: Classify PDF

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "PDF file name"
        required: true
      filecontent:
        description: "PDF base64 content"
        required: true

jobs:
  classify:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Set OpenAI API key from GitHub secret
      - run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      # 3️⃣ Decode PDF file from base64
      - run: |
          mkdir -p output_pdfs
          echo "${{ github.event.inputs.filecontent }}" | base64 -d > invoice.pdf

      # 4️⃣ Install dependencies and run Python classifier
      - run: |
          pip install --upgrade pip
          pip install openai pdfplumber PyPDF2
          python classify_invoice.py invoice.pdf output_pdfs

      # 5️⃣ Upload classified PDFs as artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: classified-pdfs
          path: output_pdfs/*.pdf
