name: Classify PDF

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "PDF file name"
        required: true
      filelink:
        description: "SharePoint PDF file link"
        required: true

jobs:
  classify:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Set OpenAI API key from secret
      - run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      # 3️⃣ Download PDF safely
      - run: |
          echo "Downloading PDF from SharePoint..."
          curl -L -o invoice.pdf "${{ github.event.inputs.filelink }}" \
            --header "Authorization: Bearer ${{ secrets.SHAREPOINT_PAT }}"
          ls -lh invoice.pdf   # confirm file exists
          file invoice.pdf     # confirm it's a valid PDF

      # 4️⃣ Install Python dependencies
      - run: |
          pip install --upgrade pip
          pip install openai pdfplumber PyPDF2 requests

      # 5️⃣ Run Python classifier
      - run: |
          python classify_invoice.py invoice.pdf output_pdfs

      # 6️⃣ Upload results
      - uses: actions/upload-artifact@v4
        with:
          name: classified-pdfs
          path: output_pdfs/*.pdf
